name: Beta Release

on:
  push:
    tags:
      - 'beta-*'

jobs:
  build-and-sign:
    name: Build and Sign Beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Install web-ext
        run: npm install -g web-ext

      - name: Package extension
        run: web-ext build
        env:
          VERSION: ${{ github.ref_name }}
          BUILD_FOR_AMO: 'true'

      - name: Sign extension
        run: |
          web-ext sign \
            --api-key=${{ secrets.AMO_API_KEY }} \
            --api-secret=${{ secrets.AMO_SECRET }} \
            --source-dir=./dist --artifacts-dir=./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: temporary-containers-beta
          path: |
            ./artifacts/*.xpi
            ./artifacts/*.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/beta-')
        with:
          files: |
            ./artifacts/*.xpi
            ./artifacts/*.zip
          draft: false
          prerelease: true
          tag_name: ${{ github.ref_name }}
          name: Temporary Containers ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
